# Linux (https://github.com/travis-ci-tester/toolchain-table)

os:
  - linux

sudo:
  - false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - python3
      # https://github.com/travis-ci-tester/travis-test-clang-cxx-11
      - libstdc++-4.8-dev
      # -- end
      # https://github.com/travis-ci-tester/travis-test-gcc-cxx-11
      - g++-4.8
      # -- end
env:
  - TOOLCHAIN=default CONFIG=Release
  - TOOLCHAIN=default CONFIG=Debug
  - TOOLCHAIN=clang-libstdcxx CONFIG=Release
  - TOOLCHAIN=clang-libstdcxx CONFIG=Debug
  - TOOLCHAIN=gcc-4-8 CONFIG=Release
  - TOOLCHAIN=gcc-4-8 CONFIG=Debug
  - TOOLCHAIN=analyze CONFIG=Release
  - TOOLCHAIN=analyze CONFIG=Debug
  - TOOLCHAIN=sanitize-address CONFIG=Release
  - TOOLCHAIN=sanitize-address CONFIG=Debug
  - TOOLCHAIN=sanitize-leak CONFIG=Release
  - TOOLCHAIN=sanitize-leak CONFIG=Debug
  - TOOLCHAIN=sanitize-thread CONFIG=Release
  - TOOLCHAIN=sanitize-thread CONFIG=Debug

install:

  # install cmake toolchains and script
  - POLLY_VERSION="0.6.1"
  - wget "https://github.com/ruslo/polly/archive/v${POLLY_VERSION}.tar.gz"
  - tar xf "v${POLLY_VERSION}.tar.gz"
  - export PATH="`pwd`/polly-${POLLY_VERSION}/bin:${PATH}"
  # -- end
  # verify installed cmake
  - which cmake
  - cmake --version
  # -- end

script:
  - build.py --toolchain ${TOOLCHAIN} --config ${CONFIG} --verbose --test
