# Windows (https://github.com/travis-ci-tester/toolchain-table)

environment:
  matrix:
    #
    - TOOLCHAIN: "default"
      CONFIG: Release

    - TOOLCHAIN: "default"
      CONFIG: Debug

    #
    - TOOLCHAIN: "ninja-vs-12-2013-win64"
      CONFIG: Release

    - TOOLCHAIN: "ninja-vs-12-2013-win64"
      CONFIG: Debug

    #
    - TOOLCHAIN: "nmake-vs-12-2013-win64"
      CONFIG: Release

    - TOOLCHAIN: "nmake-vs-12-2013-win64"
      CONFIG: Debug

    #
    - TOOLCHAIN: "nmake-vs-12-2013"
      CONFIG: Release

    - TOOLCHAIN: "nmake-vs-12-2013"
      CONFIG: Debug

    #
    - TOOLCHAIN: "vs-10-2010"
      CONFIG: Release

    - TOOLCHAIN: "vs-10-2010"
      CONFIG: Debug

    #
    - TOOLCHAIN: "vs-11-2012"
      CONFIG: Release

    - TOOLCHAIN: "vs-11-2012"
      CONFIG: Debug

    #
    - TOOLCHAIN: "vs-12-2013-win64"
      CONFIG: Release

    - TOOLCHAIN: "vs-12-2013-win64"
      CONFIG: Debug

    #
    - TOOLCHAIN: "vs-12-2013-xp"
      CONFIG: Release

    - TOOLCHAIN: "vs-12-2013-xp"
      CONFIG: Debug

    #
    - TOOLCHAIN: "vs-12-2013"
      CONFIG: Release

    - TOOLCHAIN: "vs-12-2013"
      CONFIG: Debug

    #
    - TOOLCHAIN: "vs-14-2015"
      CONFIG: Release

    - TOOLCHAIN: "vs-14-2015"
      CONFIG: Debug

    #
    - TOOLCHAIN: "vs-9-2008"
      CONFIG: Release

    - TOOLCHAIN: "vs-9-2008"
      CONFIG: Debug

    #
    - TOOLCHAIN: "mingw"
      CONFIG: Release

    - TOOLCHAIN: "mingw"
      CONFIG: Debug

install:
  - cmd: set POLLY_VERSION="0.9.0"
  - cmd: appveyor DownloadFile "https://github.com/ruslo/polly/archive/v%POLLY_VERSION%.tar.gz"
  # install ninja --
  - cmd: set NINJA_VERSION="1.6.0"
  - cmd: appveyor DownloadFile "https://github.com/ninja-build/ninja/releases/download/v%NINJA_VERSION%/ninja-win.zip"
  - cmd: cmake -E tar xf "ninja-win.zip"
  - cmd: cmake -E make_directory "ninja"
  - cmd: cmake -E rename "ninja.exe" "ninja/ninja.exe"
  - cmd: set PATH=%cd%\ninja;%PATH%
  # -- end
  - cmd: cmake -E tar xf "v%POLLY_VERSION%.tar.gz"
  - cmd: set POLLY_PATH=%cd%\polly-%POLLY_VERSION%\bin
  - cmd: set PATH=C:\Python34-x64;%PATH%
  - cmd: cmake --version
  - cmd: python --version

build_script:
  - cmd: python %POLLY_PATH%\build.py --toolchain "%TOOLCHAIN%" --config "%CONFIG%" --verbose --test
